# Generated by Django 3.0.3 on 2020-04-21 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 13, 4, 52, 876272, tzinfo=utc)),
        ),
    ]
