# Generated by Django 3.0.4 on 2020-03-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
        ('contract', '0003_auto_20200328_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
