# Generated by Django 3.0.4 on 2020-03-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20200328_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(default='waiting', max_length=100),
            preserve_default=False,
        ),
    ]
