# Generated by Django 3.0.4 on 2020-03-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_auto_20200331_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='m_type',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
    ]
